---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: etherpad
spec:
  encryptedData:
    password: AgCYeGTpOxmeO7oiPom4kDLoLg/NLp5k6rGpFuGV+WiXzXT+1OZkxGVadtLQo+47V9ygZVVVecYOB8sZb6qgpUYhy9XY0yXTIMvEe36VL94m1wDVNAzc0WrVCxIJ/BWa3PbO1LUsHWXnttM4lO15HQCJ9sAEPSFZ4RohiNskhnYTuejDQRtym3rtOBosL2HBIxwKqeasNKKxb0sRjmBXjv1boM6OOKKn6y6rvlXPqS+ZRO8J1jbEf/0DcdDNnfbUQu72Ji5xfFqaykcrAdTIRTVa8Y6i3g41RHXf17xlvQCvk/msWKfHCoRNzuy/UrjLhPHvlXod6+RKDBB+TxTuR4Pl5+wCmqTaJat1LmdUfSJfC6sWHI6vEV+q0TSFTiecOdidcJ+mjjnulQiTQC5ys96eoOx3BBRu+Fdh4bigWMs2X7ZrJLnPEPMcxXbiXAOsRacCQFbaqTJkQeiDDMM6RMCKHVAhQVv05HRBh1K3AtN5LUtlTzhI0IDvCtD5hZ532F+/Mxd9VLbji4cwOC29/xwHADYe3O7HbBxQSZx1wFO2LMbKbIs0OGyXwuAQlc/z1XkKR8N2RmxDwRYm3rqubva1IkCcnMQoYuwiJaZPNoAaP5r53ZpLlk6lk/k0DiVIqgEgVzKudlTFhG/gnrndVR2HYijxp3xQFqEEO4VSSytuWerrMC0dWR24aL5PGYf6MipBvI9ncf48wCM=
  template:
    metadata:
      name: postgres-credentials
      namespace: etherpad
    type: Opaque
